### ISSUE TITLE
关于编译这个项目的Issue.

### ISSUE THREAD

**Issue by PeinWang** [liguobao/MovieCrawler#4]
1，我发现我rebuild整个项目的时候会从Nuget上下载很多package下来，目前的大小已有1G左右。这个问题困扰了我一天，请问这是一个正常的现象吗？PS：代理服务器的网络质量不好。
2，还有一些依赖的package已经有了正式版，而从VS下载的情况来看，它似乎下载的是“-preview”的版本，请问这个是正常的吗？
3，我把project.json中的runtimes中的内容注释之后，Nuget还是会给我下载与OSX和Ubuntu相关的package，请问这个有什么可以设置的地方吗？

谢谢你。

**Comment by liguobao** [comment]
1、package大小这个没怎么留意过，我稍后去看看。
2、有些package可能是当时在1.0.1的时候引入的，对应的是preview，升级到1.1之后也没什么问题，所以我也没理它...稍后瞄下。
3. runtimes节点只是控制编译时要不要编译发布成对应平台的app，并不会影响OSX和ubuntu等平台相关package的下载。
简单来说就是：
使用dotnet publish -r ubuntu.14.04-x64 -c Release -o "C:\code\website\Dy2018Crawler"; 发布的时候，直接将此项目发布成ubuntu的app，不依赖于.net core sdk相关东西。
如果//"type": "platform" 节点保留，直接publish不指定版本，会直接生成xxx.dll,在对应平台使用dotnet xxx.dll 即可运行此程序。这样方式的话，目标平台就必须安装对应版本的.net core，不然跑不起来的。
所以....你懂的。
关于project.json,官方文档在：https://github.com/aspnet/Home/wiki/Project.json-file
张善友老师的博客：http://www.cnblogs.com/shanyou/p/5693453.html

不过为了适应MSbuild,peoject.json在下个版本的.net core(1.2)可能会被干掉。
(不造微软爸爸怎么想的...
大概如上...
@PeinWang
